### ISSUE TITLE
Migrate to specfile library

### ISSUE THREAD

**Issue by nforro** [rebase-helper/rebase-helper#884]

**Comment by FrNecas** [comment]
<h2>Notes to the migration</h2>

I started working on the migration in #888 , my approach is to start replacing from the lowest levels of manipulation and going upward (since the "main" `Specfile` class is not fully featured yet). I will try to gather some compatibility/migration notes here that may be useful for the future packit migration.

- Sections no longer have the `%` character in their names so accessing specific sections may need to change
- `Macros.expand()` raises an exception when the expansion fails rather than returning a default, a wrapper was introduced in rebase-helper for the moment
- some utility things may have to remain in rebase-helper, e.g. `get_comment_span`, `substitute_path_with_macros`
